### ISSUE TITLE
ValueError from curve_fit-call

### ISSUE THREAD

**Issue by mgrub** [eichstaedtPTB/MonteCarloHandsOn#1]
In [notebook 4](https://github.com/eichstaedtPTB/MonteCarloHandsOn/blob/master/04%20Propagating%20through%20the%20model%20function.ipynb) the scipy-function [curve_fit ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html) is used. It seems like the signature of the `sigma`-parameter has changed over the past few years and it now requires a 1D or 2D array input. 

To avoid an error message and restore the old behaviour, I suggest to change the following line of the  `In [5]:`-block:
`noise = 0.2`
to
`noise = np.full_like(t, 0.2)`

**Comment by eichstaedtPTB** [comment]
Thanks for pointing this out! Fixed with commit [6693fea](https://github.com/eichstaedtPTB/MonteCarloHandsOn/commit/6693feae52e23a19987787c7cc3761e258b35be1)
